version: "3.9"

volumes:
  postgres_data:

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./app
    image: car_sharing_web
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
  migrations:
    image: car_sharing_web
    entrypoint: python manage.py migrate
    volumes:
      - ./app:/code
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: car_sharing_nginx
    ports:
      - "1337:80"
    depends_on:
      - web
