version: "2"

volumes:
  postgres_data:

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
  web:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
  migrations:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
