version: "2"

volumes:
  postgres_data:

services:
  redis:
    image: redis
  db:
    extends:
      file: docker-compose.yml
      service: db
  web:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: gunicorn car_sharing_project.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
      - redis
  migrations:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
  celery:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: celery -A car_sharing_project worker -l info
    depends_on:
      - redis
  celery-beat:
    extends:
      file: docker-compose.yml
      service: web
    entrypoint: celery -A car_sharing_project beat -l info
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
